//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopDataModifier.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DealershipCon : DbContext
    {
        public DealershipCon()
            : base("name=DealershipCon")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<branch_office> branch_office { get; set; }
        public virtual DbSet<brands> brands { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<dealership> dealership { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<position> position { get; set; }
        public virtual DbSet<purchase> purchase { get; set; }
        public virtual DbSet<sell> sell { get; set; }
        public virtual DbSet<sold_vehicles> sold_vehicles { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<vehicles> vehicles { get; set; }
        public virtual DbSet<warehouse> warehouse { get; set; }
        public virtual DbSet<warehouse_vehicles> warehouse_vehicles { get; set; }
    }
}
