//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopDataModifier.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class naprawy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public naprawy()
        {
            this.wykonana_praca = new ObservableCollection<wykonana_praca>();
        }
    
        public long idNaprawy { get; set; }
        public decimal kwotaZaplaty { get; set; }
        public System.DateTime dataOddania { get; set; }
        public Nullable<System.DateTime> dataOdbioru { get; set; }
        public long kierownik { get; set; }
    
        public virtual naprawiane_samochody naprawiane_samochody { get; set; }
        public virtual pracownicy pracownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<wykonana_praca> wykonana_praca { get; set; }
    }
}
