//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopDataModifier.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class naprawiane_samochody
    {
        public long idSamochodu { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public string rodzaj_silnika { get; set; }
        public string rejestracja { get; set; }
        public long wlasciciel { get; set; }
    
        public virtual klienci klienci { get; set; }
        public virtual rodzaje_silnika rodzaje_silnika { get; set; }
        public virtual naprawy naprawy { get; set; }
    }
}
