//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopDataModifier
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class rodzaje_silnika
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rodzaje_silnika()
        {
            this.naprawiane_samochody = new ObservableCollection<naprawiane_samochody>();
        }
    
        public string oznaczenie_silnika { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<naprawiane_samochody> naprawiane_samochody { get; set; }
    }
}
