//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopDataModifier.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sell
    {
        public long Sin { get; set; }
        public int Vin { get; set; }
        public long EmpID { get; set; }
        public Nullable<System.DateTime> SellTime { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual purchase purchase { get; set; }
    }
}
