//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopDataModifier.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class sold_vehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sold_vehicles()
        {
            this.purchase = new ObservableCollection<purchase>();
        }
    
        public int Vin { get; set; }
        public string Brand { get; set; }
        public string Color { get; set; }
        public Nullable<int> Year { get; set; }
        public string Model { get; set; }
        public Nullable<byte> Door { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Dealership { get; set; }
        public Nullable<System.DateTime> SellTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<purchase> purchase { get; set; }
    }
}
