//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopDataModifier.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConString : DbContext
    {
        public ConString()
            : base("name=ConString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<klienci> klienci { get; set; }
        public virtual DbSet<naprawiane_samochody> naprawiane_samochody { get; set; }
        public virtual DbSet<naprawy> naprawy { get; set; }
        public virtual DbSet<nazwy_czynnosci> nazwy_czynnosci { get; set; }
        public virtual DbSet<pracownicy> pracownicy { get; set; }
        public virtual DbSet<rodzaje_silnika> rodzaje_silnika { get; set; }
        public virtual DbSet<wykonana_praca> wykonana_praca { get; set; }
    }
}
