//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopDataModifier
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class wykonana_praca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wykonana_praca()
        {
            this.pracownicy = new ObservableCollection<pracownicy>();
        }
    
        public long idPracy { get; set; }
        public string opis { get; set; }
        public Nullable<int> czasWykonania { get; set; }
        public decimal koszt { get; set; }
        public long idNaprawy { get; set; }
        public string nazwa { get; set; }
    
        public virtual naprawy naprawy { get; set; }
        public virtual nazwy_czynnosci nazwy_czynnosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<pracownicy> pracownicy { get; set; }
    }
}
