//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopDataModifier.MVVM.Model
{
    using System;
    using System.Collections.ObjectModel;
    using WorkshopDataModifier.Core;

    /// <summary>
    /// Represents a brand.
    /// </summary>
    public partial class brands : ObservableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="brands"/> class.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public brands()
        {
            this.vehicles = new ObservableCollection<vehicles>();
            this.warehouse_vehicles = new ObservableCollection<warehouse_vehicles>();
        }

        private bool _isSelected;
        /// <summary>
        /// Part of multiselect function that indicates whether the brand is selected.
        /// </summary>
        public bool IsSelected
        {
            get { return _isSelected; }
            set
            {
                _isSelected = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Gets or sets the name of the brand.
        /// </summary>
        /// <remarks>
        /// Primary key
        /// </remarks>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the collection of associated vehicles for the brand.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<vehicles> vehicles { get; set; }

        /// <summary>
        /// Gets or sets the collection of associated warehouse vehicles for the brand.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<warehouse_vehicles> warehouse_vehicles { get; set; }
    }
}
