//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopDataModifier.MVVM.Model
{
    using System;
    using System.Collections.ObjectModel;
    using WorkshopDataModifier.Core;

    /// <summary>
    /// Represents a customer.
    /// </summary>
    public partial class customer : ObservableObject
    {
        private bool _isSelected;
        /// <summary>
        /// Part of multiselect function that indicates whether the customer is selected.
        /// </summary>
        public bool IsSelected
        {
            get { return _isSelected; }
            set
            {
                _isSelected = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Gets or sets the Serial Identification Number (SIN) of the customer.
        /// </summary>
        /// <remarks>
        /// Composite primary key.
        /// </remarks>
        public long Sin { get; set; }

        /// <summary>
        /// Gets or sets the Vehicle Identification Number (VIN) of the customer.
        /// </summary>
        /// <remarks>
        /// Composite primary key.
        /// </remarks>
        public int Vin { get; set; }

        /// <summary>
        /// Gets or sets the name of the customer.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the surname of the customer.
        /// </summary>
        public string Surname { get; set; }

        /// <summary>
        /// Gets or sets the phone number of the customer.
        /// </summary>
        public string Phone { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the customer was added.
        /// </summary>
        public Nullable<System.DateTime> AddTime { get; set; }

        /// <summary>
        /// Gets or sets the associated purchase for the customer.
        /// </summary>
        public virtual purchase purchase { get; set; }
    }
}
