//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopDataModifier.MVVM.Model
{
    using System;
    using System.Collections.ObjectModel;
    using WorkshopDataModifier.Core;

    /// <summary>
    /// Represents a dealership.
    /// </summary>
    public partial class dealership : ObservableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="dealership"/> class.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dealership()
        {
            this.vehicles = new ObservableCollection<vehicles>();
            this.purchase = new ObservableCollection<purchase>();
            this.employee = new ObservableCollection<employee>();
        }

        private bool _isSelected;
        /// <summary>
        /// Part of multiselect function that indicates whether the dealership is selected.
        /// </summary>
        public bool IsSelected
        {
            get { return _isSelected; }
            set
            {
                _isSelected = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Gets or sets the name of the dealership.
        /// </summary>
        /// <remarks>
        /// Primary key
        /// </remarks>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the location of the dealership.
        /// </summary>
        public string Location { get; set; }

        /// <summary>
        /// Gets or sets the ID of the associated branch office.
        /// </summary>
        public Nullable<int> BranchID { get; set; }

        /// <summary>
        /// Gets or sets the phone number of the dealership.
        /// </summary>
        public string Phone { get; set; }

        /// <summary>
        /// Gets or sets the associated branch office for the dealership.
        /// </summary>
        public virtual branch_office branch_office { get; set; }

        /// <summary>
        /// Gets or sets the collection of associated vehicles for the dealership.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<vehicles> vehicles { get; set; }

        /// <summary>
        /// Gets or sets the collection of associated purchases for the dealership.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<purchase> purchase { get; set; }

        /// <summary>
        /// Gets or sets the collection of associated employees for the dealership.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<employee> employee { get; set; }
    }
}
