//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopDataModifier.MVVM.Model
{
    using System;
    using System.Collections.ObjectModel;
    using WorkshopDataModifier.Core;

    /// <summary>
    /// Represents a position.
    /// </summary>
    public partial class position : ObservableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="position"/> class.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public position()
        {
            this.employee = new ObservableCollection<employee>();
        }

        private bool _isSelected;
        /// <summary>
        /// Part of multiselect function that indicates whether the position is selected.
        /// </summary>
        public bool IsSelected
        {
            get { return _isSelected; }
            set
            {
                _isSelected = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Gets or sets the name of the position.
        /// </summary>
        /// <remarks>
        /// Primary key
        /// </remarks>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the collection of associated employees for the position.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<employee> employee { get; set; }
    }
}
