//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopDataModifier.MVVM.Model
{
    using System;
    using System.Collections.ObjectModel;
    using WorkshopDataModifier.Core;

    /// <summary>
    /// Represents a sell.
    /// </summary>
    public partial class sell : ObservableObject
    {
        private bool _isSelected;
        /// <summary>
        /// Part of multiselect function that indicates whether the sell is selected.
        /// </summary>
        public bool IsSelected
        {
            get { return _isSelected; }
            set
            {
                _isSelected = value;
                OnPropertyChanged();
            }
        }
        /// <summary>
        /// Gets or sets the Serial Identification Number (SIN) associated with the sell.
        /// </summary>
        /// <remarks>
        /// Composite primary key
        /// </remarks>
        public long Sin { get; set; }

        /// <summary>
        /// Gets or sets the VIN (Vehicle Identification Number) associated with the sell.
        /// </summary>
        /// <remarks>
        /// Composite primary key
        /// </remarks>
        public int Vin { get; set; }

        /// <summary>
        /// Gets or sets the employee ID associated with the sell.
        /// </summary>
        public long EmpID { get; set; }

        /// <summary>
        /// Gets or sets the sell time.
        /// </summary>
        public Nullable<System.DateTime> SellTime { get; set; }

        /// <summary>
        /// Gets or sets the associated employee.
        /// </summary>
        public virtual employee employee { get; set; }

        /// <summary>
        /// Gets or sets the associated purchase.
        /// </summary>
        public virtual purchase purchase { get; set; }
    }
}
